### ISSUE TITLE
Not require libxdf to be installed during testing

### ISSUE THREAD

**Issue by liquidg3** [neurodevs/node-xdf#1]
Is there a way to disable the checks for the libxdf library during testing?

maybe letting us add a `process.env.SHOULD_CHECK_FOR_XDF_LIB='false'` or something in our tests to disable the checks?

Thanks!

**Comment by eric-yates** [comment]
I'll look into the best way to do this @liquidg3! 

My first impression is that the best solution would be to make it so that libxdf doesn't have to be installed at all for the tests to run, which will likely require better faking. Assume that if the right inputs are passed to libxdf, they've got all their behaviors figured out by this point that actual implementations aren't necessary for testing.

**Comment by eric-yates** [comment]
@liquidg3 I committed a patch that makes the tests run without libxdf installed. Thanks for the suggestion, and let me know if you have any other requests!

**Comment by liquidg3** [comment]
Thanks dude, keep up the great work!
